eureka:
  client:
    service-url:
      defaultZone: http://localhost:8762/eureka/   # todo 2. eureka需要找到自己  todo 6.集群 两台机器互相注册
    register-with-eureka: false
    fetch-registry: false   # todo 4. 不发现自己
  instance:
    prefer-ip-address: true   # todo 7. 使得量及其互相注册 以及 使得主页面能够显示DS Replicas
  server:
    enable-self-preservation: false    #  todo 5.避免出现红色警报 EMERGENCY! EUREKA MAY BE INCORRECTLY CLAIMING INSTANCES ARE UP WHEN THEY'RE NOT.
spring:
  application:
    name: eureka  # todo 3. 更改发现的名称
#server:
#  port: 8762